// Product actions

export const PRODUCTS_UPDATE_FIELD = 'PRODUCTS_UPDATE_FIELD'
export const PRODUCTS_UPDATE_PRODUCT = 'PRODUCTS_UPDATE_PRODUCT'
export const PRODUCTS_CREATE_VARIANT = 'PRODUCTS_CREATE_VARIANT'
export const PRODUCTS_UPDATE_VARIANT = 'PRODUCTS_UPDATE_VARIANT'
export const PRODUCTS_CREATE_VARIANT_ATTRIBUTE = 'PRODUCTS_CREATE_VARIANT_ATTRIBUTE'
export const PRODUCTS_UPDATE_VARIANT_ATTRIBUTE = 'PRODUCTS_UPDATE_VARIANT_ATTRIBUTE'

// Clients actions

export const CLIENTS_UPDATE_FIELD = 'CLIENTS_UPDATE_FIELD'
export const CLIENTS_UPDATE_CLIENT = 'CLIENTS_UPDATE_CLIENT'

// Custom Attributes actions

export const CUSTOM_ATTRIBUTES_UPDATE_FIELD = 'CUSTOM_ATTRIBUTES_UPDATE_FIELD'
export const CUSTOM_ATTRIBUTES_CREATE_CUSTOM_ATTRIBUTE = 'CUSTOM_ATTRIBUTES_CREATE_CUSTOM_ATTRIBUTE'
export const CUSTOM_ATTRIBUTES_UPDATE_CUSTOM_ATTRIBUTE = 'CUSTOM_ATTRIBUTES_UPDATE_CUSTOM_ATTRIBUTE'

// Category actions

export const CATEGORIES_CREATE_CATEGORY = 'CATEGORIES_CREATE_CATEGORY'
export const CATEGORIES_UPDATE_FIELD = 'CATEGORIES_UPDATE_FIELD'

// Inventory actions

export const INVENTORIES_UPDATE_FIELD = 'INVENTORIES_UPDATE_FIELD'

// Manufacturer actions

export const MANUFACTURERS_UPDATE_MANUFACTURER = 'MANUFACTURERS_UPDATE_MANUFACTURER'
export const MANUFACTURERS_UPDATE_FIELD = 'MANUFACTURERS_UPDATE_FIELD'

// Provider actions

export const PROVIDERS_UPDATE_PROVIDER = 'PROVIDERS_UPDATE_PROVIDER'
export const PROVIDERS_UPDATE_FIELD = 'PROVIDERS_UPDATE_FIELD'

// Store actions

export const STORES_UPDATE_FIELD = 'STORES_UPDATE_FIELD'
export const STORES_UPDATE_STORE = 'STORES_UPDATE_STORE'

// User action

export const USER_UPDATE_FIELD = 'USER_UPDATE_FIELD'
export const USER_UPDATE_USER = 'USER_UPDATE_USER'

// Order actions

export const ORDERS_UPDATE_FIELD = 'ORDERS_UPDATE_FIELD'
export const ORDERS_UPDATE_ORDER = 'ORDERS_UPDATE_ORDER'

// Shipping actions

export const SHIPPINGS_UPDATE_FIELD = 'SHIPPINGS_UPDATE_FIELD'
export const SHIPPINGS_UPDATE_SHIPPING = 'SHIPPINGS_UPDATE_SHIPPING'


export const SETTINGS_UPDATE_FIELD = 'SETTINGS_UPDATE_FIELD'
export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD'
export const GLOBAL_UPDATE_FIELD = 'GLOBAL_UPDATE_FIELD'
