export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD'

export const GLOBAL_UPDATE_FIELD = 'GLOBAL_UPDATE_FIELD'

export const PROVIDERS_UPDATE_FIELD = 'PROVIDERS_UPDATE_FIELD'

export const SETTINGS_UPDATE_FIELD = 'SETTINGS_UPDATE_FIELD'

export const STORES_UPDATE_FIELD = 'STORES_UPDATE_FIELD'
export const STORES_UPDATE_STORE = 'STORES_UPDATE_STORE'

export const USER_UPDATE_FIELD = 'USER_UPDATE_FIELD'

export const MANUFACTURERS_UPDATE_FIELD = 'MANUFACTURERS_UPDATE_FIELD'
