export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD'

export const GLOBAL_UPDATE_FIELD = 'GLOBAL_UPDATE_FIELD'

// Product actions

export const PRODUCTS_UPDATE_PRODUCT = 'PRODUCTS_UPDATE_PRODUCT'
export const PRODUCTS_UPDATE_VARIANT = 'PRODUCTS_UPDATE_VARIANT'
export const PRODUCTS_UPDATE_FIELD = 'PRODUCTS_UPDATE_FIELD'

// Inventory actions

export const INVENTORIES_UPDATE_FIELD = 'INVENTORIES_UPDATE_FIELD'


// Manufacturer actions

export const MANUFACTURERS_UPDATE_MANUFACTURER = 'MANUFACTURERS_UPDATE_MANUFACTURER'
export const MANUFACTURERS_UPDATE_FIELD = 'MANUFACTURERS_UPDATE_FIELD'


// Provider actions

export const PROVIDERS_UPDATE_PROVIDER = 'PROVIDERS_UPDATE_PROVIDER'
export const PROVIDERS_UPDATE_FIELD = 'PROVIDERS_UPDATE_FIELD'

export const SETTINGS_UPDATE_FIELD = 'SETTINGS_UPDATE_FIELD'

export const STORES_UPDATE_FIELD = 'STORES_UPDATE_FIELD'
export const STORES_UPDATE_STORE = 'STORES_UPDATE_STORE'

export const USER_UPDATE_FIELD = 'USER_UPDATE_FIELD'
